spring.application.name=backend

# ??PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/petpassport
spring.datasource.username=nicktraining
spring.datasource.password=

# ????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
